// <auto-generated />
using System;
using BookingCare.Services.Schedule.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingCare.Services.Schedule.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    [Migration("20250925042332_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.AppointmentTimeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("end_time");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("StartTime", "EndTime");

                    b.ToTable("appointment_times");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.ClinicExceptionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClinicId")
                        .HasColumnType("bigint")
                        .HasColumnName("clinic_id");

                    b.Property<DateOnly>("ExceptionDate")
                        .HasColumnType("date")
                        .HasColumnName("exception_date");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId", "ExceptionDate");

                    b.ToTable("clinic_exceptions");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.DoctorDailyScheduleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<long>("PatternId")
                        .HasColumnType("bigint")
                        .HasColumnName("pattern_id");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date")
                        .HasColumnName("schedule_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatternId");

                    b.HasIndex("ScheduleDate");

                    b.HasIndex("DoctorId", "ScheduleDate")
                        .IsUnique();

                    b.ToTable("doctor_daily_schedules");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.DoctorScheduleExceptionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AppointmentTimeId")
                        .HasColumnType("bigint")
                        .HasColumnName("appointment_time_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<DateOnly>("ExceptionDate")
                        .HasColumnType("date")
                        .HasColumnName("exception_date");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("exception_type");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_available");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentTimeId");

                    b.HasIndex("ExceptionType");

                    b.HasIndex("DoctorId", "ExceptionDate");

                    b.ToTable("doctor_schedule_exceptions");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.SchedulePatternEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("FULL_DAY")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("schedule_patterns", t =>
                        {
                            t.HasCheckConstraint("CK_SchedulePattern_Name", "[name] IN ('FULL_DAY', 'MORNING_ONLY', 'AFTERNOON_ONLY', 'EVENING_ONLY')");
                        });
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.SchedulePatternSlotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AppointmentTimeId")
                        .HasColumnType("bigint")
                        .HasColumnName("appointment_time_id");

                    b.Property<long>("PatternId")
                        .HasColumnType("bigint")
                        .HasColumnName("pattern_id");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentTimeId");

                    b.HasIndex("PatternId", "AppointmentTimeId");

                    b.ToTable("schedule_pattern_slots");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.ServiceScheduleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClinicId")
                        .HasColumnType("bigint")
                        .HasColumnName("clinic_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("PatternId")
                        .HasColumnType("bigint")
                        .HasColumnName("pattern_id");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("PatternId");

                    b.HasIndex("ServiceId");

                    b.ToTable("service_schedules");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.DoctorDailyScheduleEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Schedule.Models.Entities.SchedulePatternEntity", "Pattern")
                        .WithMany("DoctorDailySchedules")
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pattern");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.DoctorScheduleExceptionEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Schedule.Models.Entities.AppointmentTimeEntity", "AppointmentTime")
                        .WithMany("DoctorScheduleExceptions")
                        .HasForeignKey("AppointmentTimeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppointmentTime");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.SchedulePatternSlotEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Schedule.Models.Entities.AppointmentTimeEntity", "AppointmentTime")
                        .WithMany("SchedulePatternSlots")
                        .HasForeignKey("AppointmentTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingCare.Services.Schedule.Models.Entities.SchedulePatternEntity", "Pattern")
                        .WithMany("SchedulePatternSlots")
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppointmentTime");

                    b.Navigation("Pattern");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.ServiceScheduleEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Schedule.Models.Entities.SchedulePatternEntity", "Pattern")
                        .WithMany("ServiceSchedules")
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pattern");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.AppointmentTimeEntity", b =>
                {
                    b.Navigation("DoctorScheduleExceptions");

                    b.Navigation("SchedulePatternSlots");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.SchedulePatternEntity", b =>
                {
                    b.Navigation("DoctorDailySchedules");

                    b.Navigation("SchedulePatternSlots");

                    b.Navigation("ServiceSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
