// <auto-generated />
using System;
using BookingCare.Services.Schedule.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingCare.Services.Schedule.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    [Migration("20251118004948_AddServiceMedicalSchedule")]
    partial class AddServiceMedicalSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.ClinicExceptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("clinic_id");

                    b.Property<DateOnly>("ExceptionDate")
                        .HasColumnType("date")
                        .HasColumnName("exception_date");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId", "ExceptionDate");

                    b.ToTable("clinic_exceptions");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.DoctorDailyScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("doctor_id");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date")
                        .HasColumnName("schedule_date");

                    b.Property<string>("SchedulePatterns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("schedule_patterns");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ScheduleDate");

                    b.HasIndex("DoctorId", "ScheduleDate")
                        .IsUnique();

                    b.ToTable("doctor_daily_schedules");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.DoctorScheduleExceptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("AppointmentTime")
                        .HasColumnType("int")
                        .HasColumnName("appointment_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("doctor_id");

                    b.Property<DateOnly>("ExceptionDate")
                        .HasColumnType("date")
                        .HasColumnName("exception_date");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("exception_type");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_available");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("ExceptionType");

                    b.HasIndex("DoctorId", "ExceptionDate");

                    b.ToTable("doctor_schedule_exceptions");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.ServiceMedicalDailyScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date")
                        .HasColumnName("schedule_date");

                    b.Property<string>("SchedulePatterns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("schedule_patterns");

                    b.Property<Guid>("ServiceMedicalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_medical_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleDate");

                    b.HasIndex("ServiceMedicalId");

                    b.HasIndex("ServiceMedicalId", "ScheduleDate")
                        .IsUnique();

                    b.ToTable("service_medical_daily_schedules");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.ServiceMedicalScheduleExceptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("AppointmentTime")
                        .HasColumnType("int")
                        .HasColumnName("appointment_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly>("ExceptionDate")
                        .HasColumnType("date")
                        .HasColumnName("exception_date");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("exception_type");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_available");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ServiceMedicalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_medical_id");

                    b.HasKey("Id");

                    b.HasIndex("ExceptionType");

                    b.HasIndex("ServiceMedicalId", "ExceptionDate");

                    b.ToTable("service_medical_schedule_exceptions");
                });

            modelBuilder.Entity("BookingCare.Services.Schedule.Models.Entities.ServiceScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("clinic_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SchedulePatterns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("schedule_patterns");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("ServiceId");

                    b.ToTable("service_schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
