syntax = "proto3";

option csharp_namespace = "BookingCare.Services.User.Protos";

package user;

// The user service definition
service UserService {
  // Get user by ID
  rpc GetUser (GetUserRequest) returns (UserResponse);
  
  // Get user by account ID
  rpc GetUserByAccountId (GetUserByAccountIdRequest) returns (UserResponse);
  
  // Create new user
  rpc CreateUser (CreateUserRequest) returns (UserResponse);
  
}

// Request messages
message GetUserRequest {
  string id = 1;
}

message GetUserByAccountIdRequest {
  string account_id = 1;
}

message CreateUserRequest {
  string account_id = 1;
  string email = 2;
  string first_name = 3;
  string last_name = 4;
  string gender = 5;
  string date_of_birth = 6; // ISO 8601 format (yyyy-MM-dd)
  string address = 7;
  string phone = 8;
  string avatar_url = 9;
}

// Response messages
message UserResponse {
  string id = 1;
  string account_id = 2;
  string email = 3;
  string first_name = 4;
  string last_name = 5;
  string full_name = 6;
  string gender = 7;
  string date_of_birth = 8; // ISO 8601 format (yyyy-MM-dd)
  string address = 9;
  string phone = 10;
  string avatar_url = 11;
}
