// <auto-generated />
using System;
using BookingCare.Services.ServiceMedical.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingCare.Services.ServiceMedical.Migrations
{
    [DbContext(typeof(ServiceMedicalDbContext))]
    partial class ServiceMedicalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingCare.Services.ServiceMedical.Models.Entities.ServiceCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("INACTIVE")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("service_categories", t =>
                        {
                            t.HasCheckConstraint("CK_ServiceCategory_Status", "status IN ('ACTIVE', 'INACTIVE')");
                        });
                });

            modelBuilder.Entity("BookingCare.Services.ServiceMedical.Models.Entities.ServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("DurationTime")
                        .HasColumnType("int")
                        .HasColumnName("duration_time");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<Guid?>("ServiceCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_category_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("INACTIVE")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("services", t =>
                        {
                            t.HasCheckConstraint("CK_Service_Status", "status IN ('ACTIVE', 'INACTIVE')");
                        });
                });


            modelBuilder.Entity("BookingCare.Services.ServiceMedical.Models.Entities.ServiceCategoryEntity", b =>
                {
                    b.HasOne("BookingCare.Services.ServiceMedical.Models.Entities.ServiceCategoryEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BookingCare.Services.ServiceMedical.Models.Entities.ServiceEntity", b =>
                {
                    b.HasOne("BookingCare.Services.ServiceMedical.Models.Entities.ServiceCategoryEntity", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ServiceCategory");
                });


            modelBuilder.Entity("BookingCare.Services.ServiceMedical.Models.Entities.ServiceCategoryEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Services");
                });

#pragma warning restore 612, 618
        }
    }
}
