using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using BookingCare.Services.Hospital.Enums;

namespace BookingCare.Services.Hospital.Models.Entities;

[Table("hospital_registrations")]
public class HospitalRegistrationEntity
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; } = Guid.NewGuid();

    // Representative Information
    [Required]
    [MaxLength(255)]
    [Column("representative_name")]
    public string RepresentativeName { get; set; } = string.Empty;

    [Required]
    [MaxLength(100)]
    [Column("representative_email")]
    public string RepresentativeEmail { get; set; } = string.Empty;

    [Required]
    [MaxLength(20)]
    [Column("representative_phone")]
    public string RepresentativePhone { get; set; } = string.Empty;

    // Hospital Information
    [Required]
    [MaxLength(255)]
    [Column("hospital_name")]
    public string HospitalName { get; set; } = string.Empty;

    [Required]
    [MaxLength(100)]
    [Column("hospital_email")]
    public string HospitalEmail { get; set; } = string.Empty;

    [Required]
    [MaxLength(20)]
    [Column("hospital_phone")]
    public string HospitalPhone { get; set; } = string.Empty;

    [Required]
    [Column("address")]
    public string Address { get; set; } = string.Empty;

    [Required]
    [Column("license_file")]
    public string LicenseFile { get; set; } = string.Empty;

    [Required]
    [Column("business_certificate_file")]
    public string BusinessCertificateFile { get; set; } = string.Empty;

    [Required]
    [Column("identity_card_file")]
    public string IdentityCardFile { get; set; } = string.Empty;

    [Required]
    [MaxLength(50)]
    [Column("tax_code")]
    public string TaxCode { get; set; } = string.Empty;

    [Required]
    [Column("status")]
    public RegistrationStatus Status { get; set; } = RegistrationStatus.PENDING;

    /// <summary>
    /// Contract number (e.g., HĐHT-2024-001)
    /// </summary>
    [MaxLength(50)]
    [Column("contract_number")]
    public string? ContractNumber { get; set; }

    [Column("contract_file")]
    public string? ContractFile { get; set; }

    /// <summary>
    /// Draft contract file URL (generated by admin, before hospital signature)
    /// </summary>
    [Column("contract_draft_file")]
    public string? ContractDraftFile { get; set; }

    /// <summary>
    /// Hospital signature image URL (base64 or blob storage URL)
    /// </summary>
    [Column("hospital_signature")]
    public string? HospitalSignature { get; set; }

    /// <summary>
    /// When the hospital signed the contract
    /// </summary>
    [Column("signed_at")]
    public DateTime? SignedAt { get; set; }

    /// <summary>
    /// Admin signature ID used for this contract
    /// </summary>
    [Column("admin_signature_id")]
    public Guid? AdminSignatureId { get; set; }

    /// <summary>
    /// Contract date (when contract was generated)
    /// </summary>
    [Column("contract_date")]
    public DateTime? ContractDate { get; set; }

    /// <summary>
    /// Contract effective date
    /// </summary>
    [Column("contract_effective_date")]
    public DateTime? ContractEffectiveDate { get; set; }

    /// <summary>
    /// Contract expiry date
    /// </summary>
    [Column("contract_expiry_date")]
    public DateTime? ContractExpiryDate { get; set; }

    [Column("hospital_id")]
    public Guid? HospitalId { get; set; }

    [Column("reason")]
    public string? Reason { get; set; }

    [Required]
    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.Now;

    [Required]
    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    // Navigation properties
    public virtual HospitalEntity? Hospital { get; set; }
    public virtual AdminSignatureEntity? AdminSignature { get; set; }
}

