<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<NoWarn>$(NoWarn);CS0436</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Protobuf Include="Protos\serviceMedical.proto" GrpcServices="Server" />
		<Protobuf Include="..\BookingCare.Services.Review\Protos\ReviewService.proto" GrpcServices="Client">
			<Link>Protos\ReviewService.proto</Link>
		</Protobuf>
		<Protobuf Include="..\BookingCare.Services.Hospital\Protos\hospital.proto" GrpcServices="Client">
			<Link>Protos\hospital.proto</Link>
		</Protobuf>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="12.0.1" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.57.0" />
		<PackageReference Include="Grpc.Net.Client" Version="2.57.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\Shared\BookingCare.Shared.Common\BookingCare.Shared.Common.csproj" />
		<ProjectReference Include="..\..\Shared\BookingCare.Shared.FileUpload\BookingCare.Shared.FileUpload.csproj" />
	</ItemGroup>
</Project>
