// <auto-generated />
using System;
using BookingCare.Services.Hospital.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingCare.Services.Hospital.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    partial class HospitalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.AdminSignatureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("position");

                    b.Property<string>("SignatureImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("signature_image_url");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("admin_signatures");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.ContractSigningTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("registration_id");

                    b.Property<string>("SignedFromIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("signed_from_ip");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("used_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("contract_signing_tokens");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("background_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("hospitals");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("hospital_images");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalRegistrationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<Guid?>("AdminSignatureId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("admin_signature_id");

                    b.Property<string>("BusinessCertificateFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("business_certificate_file");

                    b.Property<DateTime?>("ContractDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("contract_date");

                    b.Property<string>("ContractDraftFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contract_draft_file");

                    b.Property<DateTime?>("ContractEffectiveDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("contract_effective_date");

                    b.Property<DateTime?>("ContractExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("contract_expiry_date");

                    b.Property<string>("ContractFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contract_file");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contract_number");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("EkycSessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ekyc_session_id");

                    b.Property<int>("EkycStatus")
                        .HasColumnType("int")
                        .HasColumnName("ekyc_status");

                    b.Property<DateTime?>("EkycVerifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ekyc_verified_at");

                    b.Property<decimal?>("FaceMatchScore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("face_match_score");

                    b.Property<string>("HospitalEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hospital_email");

                    b.Property<Guid?>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hospital_name");

                    b.Property<string>("HospitalPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("hospital_phone");

                    b.Property<string>("HospitalSignature")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hospital_signature");

                    b.Property<string>("IdentityCardFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("identity_card_file");

                    b.Property<string>("LicenseFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("license_file");

                    b.Property<decimal?>("LivenessScore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("liveness_score");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<string>("RepresentativeEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("representative_email");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("representative_name");

                    b.Property<string>("RepresentativePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("representative_phone");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("signed_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tax_code");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AdminSignatureId");

                    b.HasIndex("HospitalEmail");

                    b.HasIndex("HospitalId");

                    b.HasIndex("RepresentativeEmail");

                    b.HasIndex("TaxCode");

                    b.ToTable("hospital_registrations");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalServiceMedicalEntity", b =>
                {
                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ServiceMedicalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_medical_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("HospitalId", "ServiceMedicalId");

                    b.ToTable("hospital_service_medicals");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalServiceTypeEntity", b =>
                {
                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_type_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("HospitalId", "ServiceTypeId");

                    b.ToTable("hospital_service_types");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalSpecialtyEntity", b =>
                {
                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("specialty_id")
                        .HasColumnOrder(1);

                    b.HasKey("HospitalId", "SpecialtyId");

                    b.ToTable("hospital_specialties");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalSubscriptionEntity", b =>
                {
                    b.Property<Guid>("HospitalSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_subscription_id");

                    b.Property<int>("AppointmentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("appointment_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DoctorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("doctor_count");

                    b.Property<DateTime>("EndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<int>("ServiceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("service_count");

                    b.Property<int>("SpecialtyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("specialty_count");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subscription_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("HospitalSubscriptionId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("HospitalId", "Status")
                        .HasDatabaseName("IX_hospital_subscriptions_hospital_active_unique")
                        .HasFilter("status IN ('ACTIVE', 'TRIAL')");

                    b.ToTable("hospital_subscriptions", t =>
                        {
                            t.HasCheckConstraint("CK_hospital_subscriptions_end_date", "end_date > start_date");

                            t.HasCheckConstraint("CK_hospital_subscriptions_status", "status IN ('ACTIVE', 'EXPIRED', 'CANCELLED', 'PENDING', 'TRIAL')");
                        });
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.SubscriptionPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("MONTHLY")
                        .HasColumnName("billing_cycle");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Features")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("features");

                    b.Property<int?>("MaxAppointments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("max_appointments");

                    b.Property<int?>("MaxDoctors")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("max_doctors");

                    b.Property<int?>("MaxServices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("max_services");

                    b.Property<int?>("MaxSpecialties")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("max_specialties");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name", "BillingCycle")
                        .IsUnique()
                        .HasDatabaseName("IX_subscription_plans_name_billing_cycle_unique");

                    b.ToTable("subscription_plans", t =>
                        {
                            t.HasCheckConstraint("CK_subscription_plans_billing_cycle", "billing_cycle IN ('MONTHLY', 'QUARTERLY', 'YEARLY')");

                            t.HasCheckConstraint("CK_subscription_plans_max_appointments", "(max_appointments IS NULL OR max_appointments >= 0)");

                            t.HasCheckConstraint("CK_subscription_plans_max_doctors", "(max_doctors IS NULL OR max_doctors >= 0)");

                            t.HasCheckConstraint("CK_subscription_plans_max_services", "(max_services IS NULL OR max_services >= 0)");

                            t.HasCheckConstraint("CK_subscription_plans_max_specialties", "(max_specialties IS NULL OR max_specialties >= 0)");

                            t.HasCheckConstraint("CK_subscription_plans_price", "price >= 0");

                            t.HasCheckConstraint("CK_subscription_plans_status", "status IN ('ACTIVE', 'INACTIVE')");
                        });
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.ContractSigningTokenEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Hospital.Models.Entities.HospitalRegistrationEntity", "Registration")
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalImageEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Hospital.Models.Entities.HospitalEntity", "Hospital")
                        .WithMany("HospitalImages")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalRegistrationEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Hospital.Models.Entities.AdminSignatureEntity", "AdminSignature")
                        .WithMany()
                        .HasForeignKey("AdminSignatureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BookingCare.Services.Hospital.Models.Entities.HospitalEntity", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminSignature");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalServiceMedicalEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Hospital.Models.Entities.HospitalEntity", "Hospital")
                        .WithMany("HospitalServiceMedicals")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalServiceTypeEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Hospital.Models.Entities.HospitalEntity", "Hospital")
                        .WithMany("HospitalServiceTypes")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalSpecialtyEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Hospital.Models.Entities.HospitalEntity", "Hospital")
                        .WithMany("HospitalSpecialties")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalSubscriptionEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Hospital.Models.Entities.HospitalEntity", "Hospital")
                        .WithMany("HospitalSubscriptions")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingCare.Services.Hospital.Models.Entities.SubscriptionPlanEntity", "SubscriptionPlan")
                        .WithMany("HospitalSubscriptions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hospital");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.HospitalEntity", b =>
                {
                    b.Navigation("HospitalImages");

                    b.Navigation("HospitalServiceMedicals");

                    b.Navigation("HospitalServiceTypes");

                    b.Navigation("HospitalSpecialties");

                    b.Navigation("HospitalSubscriptions");
                });

            modelBuilder.Entity("BookingCare.Services.Hospital.Models.Entities.SubscriptionPlanEntity", b =>
                {
                    b.Navigation("HospitalSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
