// <auto-generated />
using System;
using BookingCare.Services.Appointment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingCare.Services.Appointment.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    partial class AppointmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingCare.Services.Appointment.Models.Entities.AppointmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AppointmentTimeId")
                        .HasColumnType("int");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentUrls")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelledBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HospitalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRescheduled")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PendingNewAppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PendingNewAppointmentTimeId")
                        .HasColumnType("int");

                    b.Property<Guid?>("PendingNewDoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PendingRescheduleAction")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("RelativeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RescheduleToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RescheduleTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SoftReservedUntil")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "AppointmentDate", "AppointmentTimeId")
                        .IsUnique()
                        .HasDatabaseName("IX_Doctor_Date_Time_Unique")
                        .HasFilter("[DoctorId] IS NOT NULL AND [Status] IN ('PENDING', 'CONFIRMED')");

                    b.HasIndex("DoctorId", "AppointmentDate", "Status")
                        .HasDatabaseName("IX_Doctor_Date_Status")
                        .HasFilter("[DoctorId] IS NOT NULL");

                    b.HasIndex("PatientId", "AppointmentDate", "AppointmentTimeId")
                        .IsUnique()
                        .HasDatabaseName("IX_Patient_Date_Time_Unique")
                        .HasFilter("[RelativeId] IS NULL AND [Status] IN ('PENDING', 'CONFIRMED')");

                    b.HasIndex("PatientId", "AppointmentDate", "Status")
                        .HasDatabaseName("IX_Patient_Date_Status");

                    b.HasIndex("RelativeId", "AppointmentDate", "AppointmentTimeId")
                        .IsUnique()
                        .HasDatabaseName("IX_Relative_Date_Time_Unique")
                        .HasFilter("[RelativeId] IS NOT NULL AND [Status] IN ('PENDING', 'CONFIRMED')");

                    b.HasIndex("ServiceId", "AppointmentDate", "AppointmentTimeId")
                        .HasDatabaseName("IX_Service_Date_Time")
                        .HasFilter("[ServiceId] IS NOT NULL AND [Status] IN ('PENDING', 'CONFIRMED')");

                    b.HasIndex("ServiceId", "AppointmentDate", "Status")
                        .HasDatabaseName("IX_Service_Date_Status")
                        .HasFilter("[ServiceId] IS NOT NULL");

                    b.ToTable("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
