namespace BookingCare.Services.Hospital.Enums;

/// <summary>
/// Represents the status of a hospital registration in the workflow
/// </summary>
public enum RegistrationStatus
{
    /// <summary>
    /// Initial status - Waiting for admin review
    /// </summary>
    PENDING,

    /// <summary>
    /// Contract has been generated by admin, waiting for hospital signature
    /// </summary>
    CONTRACT_GENERATED,

    /// <summary>
    /// Hospital has signed the contract, waiting for final admin approval
    /// </summary>
    CONTRACT_SIGNED,

    /// <summary>
    /// Final approval - Hospital account has been created
    /// </summary>
    CONFIRMED,

    /// <summary>
    /// Registration has been cancelled/rejected
    /// </summary>
    CANCELLED
}

