// <auto-generated />
using System;
using BookingCare.Services.Payment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingCare.Services.Payment.Data.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20251111080452_MakeIsSubscriptionUpgradeNullable")]
    partial class MakeIsSubscriptionUpgradeNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingCare.Services.Payment.Models.Entities.BankAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("account_number");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("bank_code");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bank_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("bank_accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_bank_accounts_account_number_length", "LEN([account_number]) >= 6 AND LEN([account_number]) <= 20");

                            t.HasCheckConstraint("CK_bank_accounts_account_number_numeric", "[account_number] NOT LIKE '%[^0-9]%'");

                            t.HasCheckConstraint("CK_bank_accounts_bank_code_length", "LEN([bank_code]) >= 2 AND LEN([bank_code]) <= 10");
                        });
                });

            modelBuilder.Entity("BookingCare.Services.Payment.Models.Entities.PayOSPaymentMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentHospitalSubscriptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("current_hospital_subscription_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<bool?>("IsSubscriptionUpgrade")
                        .HasColumnType("bit")
                        .HasColumnName("is_subscription_upgrade");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint")
                        .HasColumnName("order_code");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_id");

                    b.Property<Guid?>("SubscriptionPlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subscription_plan_id");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("payos_payment_mappings");
                });

            modelBuilder.Entity("BookingCare.Services.Payment.Models.Entities.PaymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subscription_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_payments_status", "[status] IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')");

                            t.HasCheckConstraint("CK_payments_transaction_type", "[transaction_type] IN ('APPOINTMENT', 'SUBSCRIPTION')");
                        });
                });

            modelBuilder.Entity("BookingCare.Services.Payment.Models.Entities.PaymentMethodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("payment_methods", null, t =>
                        {
                            t.HasCheckConstraint("CK_payment_methods_status", "[status] IN ('ACTIVE', 'INACTIVE')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Thanh toán bằng tiền mặt",
                            Name = "CASH",
                            Status = "INACTIVE"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Thanh toán bằng thẻ tín dụng",
                            Name = "CREDIT_CARD",
                            Status = "INACTIVE"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Chuyển khoản ngân hàng",
                            Name = "BANK_TRANSFER",
                            Status = "INACTIVE"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Thanh toán qua MoMo",
                            Name = "MOMO",
                            Status = "INACTIVE"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Thanh toán qua ZaloPay",
                            Name = "ZALOPAY",
                            Status = "INACTIVE"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Thanh toán qua VNPay",
                            ImageUrl = "https://vnpay.vn/s1/statics.vnpay.vn/2023/6/0oxhzjmxbksr1686814746087.png",
                            Name = "VNPAY",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Thanh toán qua PayOS",
                            ImageUrl = "https://payos.vn/docs/img/logo.svg",
                            Name = "PAYOS",
                            Status = "ACTIVE"
                        });
                });

            modelBuilder.Entity("BookingCare.Services.Payment.Models.Entities.RefundHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("BankAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bank_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_id");

                    b.Property<Guid?>("ProcessedByStaffId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("processed_by_staff_id");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("refund_amount");

                    b.Property<string>("RefundReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("refund_reason");

                    b.Property<string>("StaffNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("staff_notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TransferDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("transfer_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("PaymentId");

                    b.ToTable("refund_histories", null, t =>
                        {
                            t.HasCheckConstraint("CK_refund_histories_refund_amount_positive", "[refund_amount] > 0");

                            t.HasCheckConstraint("CK_refund_histories_status", "[status] IN ('WAITING', 'PENDING', 'COMPLETED')");

                            t.HasCheckConstraint("CK_refund_histories_transfer_date_completed", "([status] = 'COMPLETED' AND [transfer_date] IS NOT NULL) OR ([status] != 'COMPLETED')");
                        });
                });

            modelBuilder.Entity("BookingCare.Services.Payment.Models.Entities.PayOSPaymentMappingEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Payment.Models.Entities.PaymentEntity", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_payos_payment_mappings_payment_id");
                });

            modelBuilder.Entity("BookingCare.Services.Payment.Models.Entities.PaymentEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Payment.Models.Entities.PaymentMethodEntity", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_payments_payment_method_id");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("BookingCare.Services.Payment.Models.Entities.RefundHistoryEntity", b =>
                {
                    b.HasOne("BookingCare.Services.Payment.Models.Entities.BankAccountEntity", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_refund_histories_bank_account_id");

                    b.HasOne("BookingCare.Services.Payment.Models.Entities.PaymentEntity", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_refund_histories_payment_id");

                    b.Navigation("BankAccount");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BookingCare.Services.Payment.Models.Entities.PaymentMethodEntity", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
